version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1q2w3e4r@#$
    ports:
      - "1433:1433"
    networks:
      - taskmanager-network

  taskmanager-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskmanager-api
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=TaskManagerDb;User=sa;Password=1q2w3e4r@#$;TrustServerCertificate=true;
    ports:
      - "5001:5001"  # Porta exposta para a API
    networks:
      - taskmanager-network
    command: /bin/bash -c "dotnet ef database update && dotnet TaskManager.Api.dll"

networks:
  taskmanager-network:
    driver: bridge
